hash-format = "sha256"

[[files]]
file = "config/aether-client.toml"
hash = "5f86c7d27a7576e13924af41a478730fc5ac1a9a0bf3b6b0ed71307c486c3ae8"

[[files]]
file = "config/aether-common.toml"
hash = "920823549f789967bd6e8ce93fe1d12d7783e10d6035bd55825e62407ff3a45b"

[[files]]
file = "config/aether-server.toml"
hash = "7f59fe620227c4e1f878b29911b708689cf0a820802b871b3f6544ee560f1fa9"

[[files]]
file = "config/aether-startup.toml"
hash = "3e0c6f3c7c02fa1a08015b944fc3a350540a256c99930a1865cca0fb91ae21c0"

[[files]]
file = "config/biomesoplenty/biome_toggles.json"
hash = "1204c73b832b07d81588def230161d03f0385cadfdc670f490fab343f54ef380"

[[files]]
file = "config/default_files/server-icon.png"
hash = "9e42bc90ce4dcea8b54aab719b95ef862028d4e8a5d97220e91e8a13c388ce01"

[[files]]
file = "config/default_files/server.properties"
hash = "95d25d490a1a868a6b8bc0992c1eef7ff355ba581d8a0d5f9939e6c488c59aab"

[[files]]
file = "config/default_files/servers.dat"
hash = "cf66502d788633ff5ce5c84c4000a5cbf0800932a7c009cf92598f31104cf821"

[[files]]
file = "config/fml.toml"
hash = "e79fe3a8ddb568b39721b268deeec42e1f88c831d580b8fb47942fec25031436"

[[files]]
file = "config/irons_spellbooks-client.toml"
hash = "52e9446f8cb7d778a86aa1eb632610de982f6e00d98eb9097e4ef3018c3cea15"

[[files]]
file = "config/irons_spellbooks-server.toml"
hash = "b3ede727a5c3d77ad0b37669e7a593c95015416b185ac4929e8b540398700a1f"

[[files]]
file = "config/jade/jade.json"
hash = "445a65bafc2ca407a91ce47f305d64c3c859cf103ed9ca29732c897276b53637"

[[files]]
file = "config/jade/plugins.json"
hash = "61e1c0b0fd38d919c5ba0368e80e6d7db80ee36d9121623b3df492dce1167475"

[[files]]
file = "config/modernfix-mixins.properties"
hash = "c136d858abc7e55a4a0690615c1f9996098aba428139790ce2bf5ab51fcf9817"

[[files]]
file = "config/server-splashes.txt"
hash = "ade7e3aec06c2b3c0e2966151d0cd8bf6405e2171757b0dc6e369772a4e8ae4a"

[[files]]
file = "config/sophisticatedbackpacks-common.toml"
hash = "2100d80af7e8e541c3a0e97dbe69c42ce29b963c4d410e93f989da43ae8f29a4"

[[files]]
file = "config/sophisticatedbackpacks-server.toml"
hash = "e9bcf52f09cacd1e3d9b072bb620e1ee455351a21ea892fed2c8482b6e29743b"

[[files]]
file = "config/sophisticatedcore-common.toml"
hash = "7e8e972645572d54c255fdb878e76cfc61ca46dbbc48a3d4d30117da24ee58a9"

[[files]]
file = "config/waystones-common.toml"
hash = "583da24ec415bf64d7752df1a8d916b1ad4dc2ba160e682ebbe3d2c77422617f"

[[files]]
file = "config/xaerominimap-common.txt"
hash = "9c809e5dc50075f1562ac808e092e1d7521f7679f99a525d9c0492baf74cc272"

[[files]]
file = "config/xaeroworldmap-common.txt"
hash = "be7330bfe1a41b7cbf3578bef78e5542bccdea1110cf66adb545e564aab23193"

[[files]]
file = "mods/aether.pw.toml"
hash = "cc3f6e6e8f1838d16e47cce9241e32176279673efb1438ff4451ccffa9579b14"
metafile = true

[[files]]
file = "mods/appleskin.pw.toml"
hash = "3b5f3feca8b299f947ed3956e49f7c3940793754928f2f99cad936448208a501"
metafile = true

[[files]]
file = "mods/balm.pw.toml"
hash = "547660bb17452fae6e46504c87eea9e75eeb50de440495cadcee9ad49c6d131d"
metafile = true

[[files]]
file = "mods/biomes-o-plenty.pw.toml"
hash = "9b1610cd28c49d34ce2fd760d208fb569f0e20055fee4c81ed4da6489b340312"
metafile = true

[[files]]
file = "mods/create.pw.toml"
hash = "9da22561c3a5e45beb91121518a49f2e8a62bedb332574ce43a9d9b287ebc705"
metafile = true

[[files]]
file = "mods/createaddition.pw.toml"
hash = "b5bbbdef134fb735d4a741ccb85b46c6b1707e8e974a09bdcc1dcd785c0f172e"
metafile = true

[[files]]
file = "mods/curios.pw.toml"
hash = "36debf7653e95a855b4fedacc19027cf2e01960fc0b6d55ef2ffbffbcb455690"
metafile = true

[[files]]
file = "mods/decent-discord-bridge.pw.toml"
hash = "103eee9afa98e895ae869a1482a39dc61fd569b3a556d36b4d35c740cda772e3"
metafile = true

[[files]]
file = "mods/default-files.pw.toml"
hash = "55078861f033521e0b31923e0ed415f44a48600718e806b0aeaac4bd3df6733c"
metafile = true

[[files]]
file = "mods/dmr.pw.toml"
hash = "f0849fc220ab38735f36e04cfeb3bebed09df20194199bcb542cfbf93a240a6e"
metafile = true

[[files]]
file = "mods/farmers-delight.pw.toml"
hash = "b75ba223cc0d159d38890b0c5db42e9454210f874dd0d0b9060f8277e803a5d8"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "73360e397134d238ee8fd21d33fd7f9275e9441f74f8f1b6ed92278877c0b9f1"
metafile = true

[[files]]
file = "mods/geckolib.pw.toml"
hash = "415ae259d7d6c92717710d6f80494d9f3c0884c6a2a35f993ad31e287f64632f"
metafile = true

[[files]]
file = "mods/glitchcore.pw.toml"
hash = "dbd756dd9bb17e6ecebcf2d7052a67a2da1c7dd378bc2089bc154916080fe031"
metafile = true

[[files]]
file = "mods/immersive-aircraft.pw.toml"
hash = "4c37eaf3699772d79e57aa0804685acb4ceb65eaee66a285a0039b0397b422b7"
metafile = true

[[files]]
file = "mods/immersive-furniture.pw.toml"
hash = "2c3b11ad8600d216d09491fc05bfd0c378c648d23f7616f23bbb18716778ff6f"
metafile = true

[[files]]
file = "mods/irons-spells-n-spellbooks.pw.toml"
hash = "90afda98f72c6834301b3ccbe6f25757c8dc2a11701c6418050ae31288c2e3ea"
metafile = true

[[files]]
file = "mods/jade.pw.toml"
hash = "b6e0a61fea06f8d6d8e1672cf07b682625c4b74efd548d5093cd9c1fed167eec"
metafile = true

[[files]]
file = "mods/jei.pw.toml"
hash = "5367193d3f87b7bc5a81bcd64a5b96a843e76d4df7a83c8bb7e1911aa82dd52e"
metafile = true

[[files]]
file = "mods/kotlin-for-forge.pw.toml"
hash = "27302b0087cf53570cd7a3b4eb550a208cbb6f6ba07210c604176155f39e0078"
metafile = true

[[files]]
file = "mods/macaws-furniture.pw.toml"
hash = "52019f01292cb860fa135485f941fff42f97910267bf122f2f797e31109bb93f"
metafile = true

[[files]]
file = "mods/mcdonalds-structure.pw.toml"
hash = "c34611496de00d4b9526d5b4288135560d1f84e26d9f90d902563e094d32d533"
metafile = true

[[files]]
file = "mods/mes-moogs-end-structures.pw.toml"
hash = "f4db358ab5081831cb84f4d81338b21f0600675ab25b13f8824deecc82d2acc8"
metafile = true

[[files]]
file = "mods/moogs-structure-lib.pw.toml"
hash = "44b52fc7e10142b0f514c66dbc0c74a0feae35ee329c37454e08aa1187d1d60e"
metafile = true

[[files]]
file = "mods/motdextender9000.pw.toml"
hash = "9070e718494a47c80e4d23df6660f3a53cdaef417c902556ccc5bf73548eb68a"
metafile = true

[[files]]
file = "mods/owo-lib.pw.toml"
hash = "46831c04077a06df823bcd0f254833a90a9a9ccc78f5069f4b4c27fa301ac0cf"
metafile = true

[[files]]
file = "mods/playeranimator.pw.toml"
hash = "93284ca7f2f23f0bb76d42b797cabf2aea1914ee9825bec82bf6ffe4c60dda0d"
metafile = true

[[files]]
file = "mods/ribbits.pw.toml"
hash = "6a598c073aabc968d8ee736141d238c517e13662f3de0feb81796cb9c0d6f4f0"
metafile = true

[[files]]
file = "mods/sophisticated-backpacks.pw.toml"
hash = "765832eca01cad73acbfac6ed74cb0169cc14ca6c9e7c9b5396cd2d7bdaa547c"
metafile = true

[[files]]
file = "mods/sophisticated-core.pw.toml"
hash = "a12227faef5279cf7afbf3520aed9b23438f309ec9b39463aaf7285a84a0fc78"
metafile = true

[[files]]
file = "mods/target-dummy.pw.toml"
hash = "85cb36f78213bb439937fd040e92a181a0bd4b1b37639af6ec30a8907de44164"
metafile = true

[[files]]
file = "mods/terrablender.pw.toml"
hash = "15962183bec2468058c70e87aa32e902a08489b0f86741088cdc9aa958ba4931"
metafile = true

[[files]]
file = "mods/toms-storage.pw.toml"
hash = "c743ea0e4f9021ef5f2fd093006e04031da11b933a0a54d86ef77bc13f4965cb"
metafile = true

[[files]]
file = "mods/waystones.pw.toml"
hash = "63ac7bf3b3599b671fae69e0ad7176610e592cc013c8b3fafbc4af10e9c66df0"
metafile = true

[[files]]
file = "mods/xaeros-minimap.pw.toml"
hash = "02e2acc15a8c1b7bbe44a64af68574d7e024f1c45504a6997568c9fcbab3846b"
metafile = true

[[files]]
file = "mods/yungs-api.pw.toml"
hash = "d9c0c9209bac0b693af2a7c1e47ffb28d366bad19c91df31dc6d345fa75250a1"
metafile = true
