name = "4430 Mods"
author = "fwfy"
version = "1.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e8c114052f88b76f33afd9b8766f9f594b847910cf3e0a67baed00579aa78316"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.217"
