name = "4430 Mods"
author = "fwfy"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1d14bee726364e85a63ed4e2bceb9829a1938974d325f3908cbd7d3a6db96a2b"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.217"
