name = "4430 Mods"
author = "fwfy"
version = "1.0.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fd23380a8aed63adf7f9b6bea6844457474445b00060ca6745d5e7a126b87c3f"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.217"
