name = "4430 Mods"
author = "fwfy"
version = "1.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a1ef159c24f6cd5ede836dc2637e34adaaeb6ac17840286911cd02bb3b9fa6aa"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.217"
