name = "4430 Mods"
author = "fwfy"
version = "1.0.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a35a39ddcf659530de0d5b96a3d6301c5fbb15b070631376906df1b850dcf142"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.217"
