name = "4430 Mods"
author = "fwfy"
version = "1.0.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f1f5753d3c6dd25b526044fea3af74993f530ffff3acfedbe4109d2cf01f26e8"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.217"
