name = "4430 Mods"
author = "fwfy"
version = "1.0.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9fa6de9e6d9d7285e9b18f398f8c6a627bff59438d9153a85d2aac31006ca950"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.217"
