name = "4430 Mods"
author = "fwfy"
version = "1.0.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "70e80136c1017f93c029646ba035c567f6d0bb8c39093ff645ff7ff0209c3935"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.217"
