name = "4430 Mods"
author = "fwfy"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b0e6143321402b3049f4b609360f9d35bdf936d2253fcb7a5b5da8f29e9ac125"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.217"
